// Code generated by ObjectBox; DO NOT EDIT.

package main

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

// ObjectBoxModel declares and builds the model from all the entities in the package.
// It is usually used when setting-up ObjectBox as an argument to the Builder.Model() function.
func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()
	model.GeneratorVersion(6)

	model.RegisterBinding(ResourceBinding)
	model.RegisterBinding(MashStepBinding)
	model.RegisterBinding(RecipeBinding)
	model.RegisterBinding(UsedResourceBinding)
	model.LastEntityId(4, 4113036754004893734)

	model.LastRelationId(4, 2025680423898785750)

	return model
}
