// Code generated by ObjectBox; DO NOT EDIT.

package main

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

// ObjectBoxModel declares and builds the model from all the entities in the package.
// It is usually used when setting-up ObjectBox as an argument to the Builder.Model() function.
func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()
	model.GeneratorVersion(6)

	model.RegisterBinding(ResourceBinding)
	model.RegisterBinding(RecipeBinding)
	model.LastEntityId(2, 7524476822026071533)

	model.LastRelationId(3, 441495759427462681)

	return model
}
