// Code generated by ObjectBox; DO NOT EDIT.

package main

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

// ObjectBoxModel declares and builds the model from all the entities in the package.
// It is usually used when setting-up ObjectBox as an argument to the Builder.Model() function.
func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()
	model.GeneratorVersion(6)

	model.RegisterBinding(MaltBinding)
	model.RegisterBinding(HopBinding)
	model.RegisterBinding(YeastBinding)
	model.RegisterBinding(RecipeBinding)
	model.LastEntityId(4, 5545330947338169134)

	model.LastRelationId(3, 3948881283661029309)

	return model
}
